name: Send PR Event to Salesforce

on:
  push:
    branches:
      - "**"

jobs:
  notify-salesforce:
    runs-on: ubuntu-latest

    steps:

      - name: Get Salesforce Token
        id: auth
        run: |
          RESPONSE=$(curl -s https://test.salesforce.com/services/oauth2/token \
            -d "grant_type=password" \
            -d "client_id=${{ secrets.SF_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.SF_CLIENT_SECRET }}" \
            -d "username=${{ secrets.SF_USERNAME }}" \
            -d "password=${{ secrets.SF_PASSWORD }}${{ secrets.SF_SECURITY_TOKEN }}")

          ACCESS_TOKEN=$(echo $RESPONSE | jq -r '.access_token')
          INSTANCE_URL=$(echo $RESPONSE | jq -r '.instance_url')

          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
          echo "INSTANCE_URL=$INSTANCE_URL" >> $GITHUB_ENV

      - name: Send Platform Event
        run: |
          curl -X POST "$INSTANCE_URL/services/data/v60.0/sobjects/Git_Merge_Request_Event__e" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "GIT_Repository__c": "${{ github.repository }}",
            "GIT_Branch__c": "${{ github.event.pull_request.head.ref }}",
            "GIT_Commit_Id__c": "${{ github.event.pull_request.head.sha }}",
            "GIT_Author__c": "${{ github.actor }}"
          }'
